### ISSUE TITLE
Create a reverse proxy server

### ISSUE THREAD

**Issue by twifkak** [google/sxg-rs#250]
Create a reverse proxy server in Rust, similar to [Web Packager Server](https://github.com/google/webpackager/blob/main/cmd/webpkgserver/README.md) as a wrapper around the `sxg_rs` library. This could be run as a typical server or as a service on [Google Cloud Run](https://cloud.google.com/run) ([see docs](https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-service-other-languages)).

**Comment by twifkak** [comment]
Of the available libraries for implementing a reverse proxy, [hyper-reverse-proxy](https://github.com/felipenoris/hyper-reverse-proxy) seems like the most accurate (removing hop-by-hop headers including those in `Connection`, etc.). Optionally we could layer on [warp](https://github.com/seanmonstar/warp) routing for the non-proxied URLs (cert-chain+cbor and validity).

We should also set `X-Forwarded-Host`, `Forwarded: host=`, and `Via` in outgoing requests; not done by that lib.

We'll need some storage/sync mechanism for ACME & OCSP.

Alternatives considered:
- [warp-reverse-proxy](https://github.com/danielSanchezQ/warp-reverse-proxy/blob/master/src/lib.rs)
- [actix_proxy](https://github.com/jofas/actix_proxy/blob/master/src/lib.rs)
- possibly some others I already forgot after closing the tabs

**Comment by twifkak** [comment]
Another server exists [in `playground/`](https://github.com/google/sxg-rs/blob/main/playground/src/server/index.ts) but it would take more effort to productionize (e.g. add all the above + the features in hyper-reverse-proxy), and it would add node as a dependency. Would be nice to have something that runs in Rust only.

**Comment by twifkak** [comment]
@antiphoton @quangIO It appears hyper requires async fns to implement `Send` for multithreading ([see details](https://blog.rust-lang.org/inside-rust/2019/10/11/AsyncAwait-Not-Send-Error-Improvements.html)). SxgWorker fns do not implement `Send` for a variety of reasons.

1. `js_sys` doesn't implement `Send`.
2. `dyn` doesn't implement `Send` unless specified (`dyn Foo + Send`) -- which would break `js_sys` support.
3. Probably more reasons.

Options to solve this:

1. `block_on()` SxgWorker fns. Presumably this eliminates parallelism -- perhaps that's OK for computations that aren't I/O bound?
2. Remove `dyn` from the code base; use type parameters instead. Simplest conceptually, but adds line noise and brittleness -- whenever we add a new type parameter, we have to update all callers.
3. Change types like `Runtime` to traits with `Send` and non-`Send` impls. Least line noise, but a bit of duplication.

I'm leaning towards 3 where possible, falling back to 2 for less pervasive types. However, I'm not an expert in Rust. Would appreciate your opinions. It seems @quangIO was considering 2 in #278; what are the implications for WasmWorker?

**Comment by antiphoton** [comment]
Traits with `async` functions can't implement `Send`, hence `Fetcher`, `Signer`, and `Storage` do not implement `Send`, hence struct `Runtime` does not implement `Send`.
`Box<dyn Fetcher>`, `Arc<dyn Fetcher>` and `Arc<F: Fetcher>` can't implement `Send` as long as `Fetcher` does not implement `Send.

I would suggest constructing `Runtime` inside `hyper`'s handler function, so that the `Runtime` is not sent between threads.

**Comment by twifkak** [comment]
> I would suggest constructing `Runtime` inside `hyper`'s handler function, so that the `Runtime` no longer need to be sent between threads.

I'm already attempting to construct it inside the closure passed to [`service_fn`](https://docs.rs/hyper/latest/hyper/service/fn.service_fn.html), and that's resulting in the "Future is not Send" error [1]. I'm not positive, but I believe the multithreading runtime needs each individual task to implement `Send` because it reserves the right to reschedule it on a different thread; [see Tokio docs](https://tokio.rs/tokio/tutorial/spawning#send-bound).

[1] In particular, it's not the call to `service_fn` but to [`server::Builder::serve`](https://docs.rs/hyper/latest/hyper/server/struct.Builder.html#method.serve) that triggers the error.

**Comment by twifkak** [comment]
I'll give it another day of effort, but if that fails, I may just try [`spawn_blocking`](https://docs.rs/tokio/1.18.2/tokio/task/fn.spawn_blocking.html) and test that it can handle concurrent requests. I note that warp calls the handler [synchronously](https://github.com/seanmonstar/warp/blob/3ff2eaf41eb5ac9321620e5a6434d5b5ec6f313f/src/filter/map.rs#L53) and warp probably knows what it's doing.

I found myself wanting for language features:
- [Constraint kinds](https://gist.github.com/withoutboats/8b0eb3012203244bcf3a4e1a4be8819c) so I didn't have to duplicate code between `RuntimeSend` and `RuntimeNoSend` impls.
- [Type-changing struct update](https://rust-lang.github.io/rfcs/2528-type-changing-struct-update-syntax.html) since our tests use the struct update syntax quite heavily, but that won't work if we get rid of `dyn`.

**Comment by antiphoton** [comment]
In WebAssembly applications with `JsValue`, `Runtime` is `!Send`; in pure Rust applications, `Runtime` is `Send`.

We may use the conditional compilation in Rust (like pre-defined macro in C++), and declare `Runtime`, `Fetcher`, `Signer` as `!Send` only when the `wasm` feature is enabled in `sxg-rs` (like [this](https://github.com/google/sxg-rs/blob/89b13cc1bc670032f777cd36ea33ee260a9b8295/sxg_rs/src/fetcher/mod.rs#L15-L16)).

**Comment by twifkak** [comment]
Oh, really good idea.

**Comment by twifkak** [comment]
TODO: Refactor this pattern from #314 into a macro in utils:

```rust
#[cfg_attr(feature = "wasm", async_trait(?Send))]
#[cfg_attr(not(feature = "wasm"), async_trait)]
```

**Comment by twifkak** [comment]
Abandoning the [attribute macro](https://doc.rust-lang.org/reference/procedural-macros.html#attribute-macros) idea, as the maintenance overhead is not worth the benefit. It would [require an additional `proc-macro` crate](https://github.com/rust-lang/rust/issues/72201).
