### ISSUE TITLE
Add User-Agent sniffing

### ISSUE THREAD

**Issue by twifkak** [google/sxg-rs#395]
Chromium M73 enabled SXG, but before [this commit](https://source.chromium.org/chromium/chromium/src/+/63526b1d9624fff4b75f19dbea47b7dd6a6e36c3) landed in [M79](https://chromiumdash.appspot.com/commits?commit=63526b1d9624fff4b75f19dbea47b7dd6a6e36c3&platform=Linux), it had an Accept header that matches the [PrefersSxg logic](https://github.com/google/sxg-rs/blob/5f4cdb2ca0ac00b007459ab94fc24069aab37ea0/sxg_rs/src/headers.rs#L434-L436) that is meant to differentiate SXG crawlers from SXG browsers, per [this recommendation](https://github.com/google/webpackager/tree/main/cmd/webpkgserver#content-negotiation).

Without User-Agent sniffing to rule out Chromium M73-78, sxg-rs may result in broken experiences on those browsers on sites that use a [service worker caching strategy](https://developer.chrome.com/docs/workbox/caching-strategies-overview/), due to [Chromium not interpreting SXG served from a SW](https://crbug.com/898733). Those browsers represent [~0.19% of users](https://caniuse.com/usage-table).

(This doesn't happen on Cloudflare Automatic Signed Exchanges because they've implemented this UA sniffing downstream.)

**Comment by twifkak** [comment]
This should be a "denylist" approach -- allowing most user agents *except* those that match Chromium 73-78.

**Comment by twifkak** [comment]
I found a few UA parsers in crates, in descending popularity:

- [woothee](https://crates.io/crates/woothee) -- huge (820kB)
- [uaparser](https://crates.io/crates/uaparser) -- huge (813kB)
- [user-agent-parser](https://crates.io/crates/user-agent-parser)
- [uap-rust](https://crates.io/crates/uap-rust)
- [fast_uaparser](https://crates.io/crates/fast_uaparser)
- [device-detector](https://crates.io/crates/device-detector)

We should rule out the huge ones, since we have serverless bundle size constraints to meet.

Perhaps a regex will suffice for our needs? Famous last words.

**Comment by quangIO** [comment]
I think a small heuristic without regex should be the way to go. For example, find `Chrome/` or `Chromium/` then get the next 2 digits to see if it is in [73, 78] range.

**Comment by twifkak** [comment]
Perhaps I'm a bit too [forward-looking](https://web.dev/chrome-firefox-100/) but there may eventually be a Chrome 730. :wink:

Are you concerned around new dependencies because of bundle size, security, performance, or something else? 

In general, I prefer accurate parsers because inaccurate ones lead to weird ecosystem effects:
 1. sites begin to target bugs in the parsers, either deliberately (e.g. the IE [star hack](https://www.evotech.net/blog/2007/04/ie7-only-css-hacks/#star)) or accidentally, and then
 2. changes to the standard need to keep in mind backwards-compatibility with these hacks, and then
 3. the semantics get progressively more complex (e.g. HTML [adoption agency algorithm](https://html.spec.whatwg.org/multipage/parsing.html#adoption-agency-algorithm) and others leading to cases where you can construct non-tree DOMs)

That said, I'm also a pragmatist. In particular, sxg-rs is a drop in the bucket -- it probably won't materially effect the destiny of User-Agent. :grin:

**Comment by antiphoton** [comment]
[user-agent-parser](https://github.com/magiclen/user-agent-parser/blob/e6ad9453b154282e547c9404c216c53eb775736b/README.md?plain=1#L10), [uap-rust](https://github.com/yaccio/uap-rust/blob/b63fc3351a7783734abdb8705c574799fd44b541/src/parser.rs#L26) and [fast_uapperser](https://gitlab.com/philbooth/uaparser-rs/-/blob/6815654f2f08b815871a9d916a80882666901964/build.rs#L31) are all internally using [regular expressions](https://github.com/ua-parser/uap-core/blob/dc85ab2628798538a2874dea4a9563f40a31f55a/regexes.yaml) defined in `uap-core`.

Picking the Chrome-related regex in `uap-core` is suffice to parse the Chrome major version.

However, adding `regex` crate as dependency increases the gzipped WASM size from 737 kB to 954 kB.

**Comment by twifkak** [comment]
Oh, thanks for the investigation @antiphoton. I overestimated the degree to which UA strings can be accurately parsed. I'll withdraw my earlier comment (except to be mindful of more than two digits).

Maybe something like " Chrome/" or " Chromium/" (note the leading space) followed by any number of digits? No need for regex then, I suppose? std::string or nom will probably suffice?
