### ISSUE TITLE
Make Signer Trait more flexible on asn1 formating

### ISSUE THREAD

**Issue by antiphoton** [google/sxg-rs#45]
The [js_signer](https://github.com/google/sxg-rs/blob/9cf0f355e2993716c71c576c69743cb25e54b1a4/sxg_rs/src/signature/js_signer.rs) mod formats signature as asn1 [in the rust code](https://github.com/google/sxg-rs/blob/9cf0f355e2993716c71c576c69743cb25e54b1a4/sxg_rs/src/signature/js_signer.rs#L42), because the [current TypeScript implementation](https://github.com/google/sxg-rs/blob/main/cloudflare_worker/worker/src/signer.ts#L33-L43) does not do the asn1 formatting.

However, there is a posibility that some JavaScript signer already includes the asn1 formatting. We should provide the flexibility to disable the asn1 formatting in the Rust code.

**Comment by antiphoton** [comment]
Instead of having the single [JsSigner::new](https://github.com/google/sxg-rs/blob/9cf0f355e2993716c71c576c69743cb25e54b1a4/sxg_rs/src/signature/js_signer.rs#L24-L28), we can make the change to have two public constructors
```Rust
impl JsSigner {
    // The JS function should be of type
    // `(input: Uint8Array) => Promise<Uint8Array>`.
    // The JS function returns the raw signature, which contains exactly 64 bytes.
    pub fn new(js_function: JsFunction) -> Self {
          todo!()
    }
    // The JS function should be of type
    // `(input: Uint8Array) => Promise<Uint8Array>`.
    // The JS function returns the signature in ASN1 format.
    pub fn new_with_asn1(js_function: JsFunction) -> Self {
          todo!()
    }
}
```

**Comment by oliy** [comment]
This sounds reasonable.
